### ISSUE TITLE
config.assets.prefix + image-path() unexpected behaviour?

### ISSUE THREAD

**Issue by guillem-catala** [rails/sass-rails#118]
Hello, 

I have set an asset prefix in application.rb 
    config.assets.prefix = "assets/static" 

and in sass i use
        background: url(image-path("logo.png"));

In development mode, when I access the site, the url rendered is
     background: url("http://www.mysite.dev:3000/assets/logo.png");

and I think it should be
    background: url("http://www.mysite.dev:3000/assets/static/logo.png");

and if I use rails helper image_tag, the url shows correctly /assets/static/logo.png

I am using latest bundles
rails (3.2.6)
sass (3.1.19)
sass-rails (3.2.5)

Any ideas? Thanks in advance!

**Comment by ypresto** [comment]
Same issue here, but I'm using `image-url()`.

**Comment by ypresto** [comment]
`rails (rake for rails < 5) tmp:cache:clear` (or `rm -rf tmp/cache/assets`)  fixed it.
