### ISSUE TITLE
NoMethodError on line ["32"] lib/sass/rails/helpers.rb: undefined method '[]' for nil:NilClass

### ISSUE THREAD

**Issue by rmontgomery429** [rails/sass-rails#121]
I'm running `bundle exec compass compile -e production --force` and I'm getting 

`NoMethodError on line ["32"] of /Users/rmontgomery429/.rvm/gems/ruby-1.9.3-p194@usertesting-orders/gems/sass-rails-3.2.5/lib/sass/rails/helpers.rb: undefined method '[]' for nil:NilClass
`

That code in question is this: `lib/sass/rails/helpers.rb:32`

``` ruby
31: def resolver
32:   options[:custom][:resolver]
33: end
```

I added a `binding.pry` to the resolver method and `options[:custom]` returns nil.

``` ruby
def resolver
  binding.pry if options[:custom].nil?
  options[:custom][:resolver]
end
```

`options.has_key? :custom` returns false.

**Comment by henrik** [comment]
I got this error trying to precompile assets in Rails 3 (with sass-rails-3.2.6) using Uglifier 2. Since Uglifier 2 is declared as backwards-incompatible, I guess it might simply be that these versions of these libs are incompatible. Rails 3 can't use a later version of sass-rails.
