### ISSUE TITLE
@font-face still doesn't work

### ISSUE THREAD

**Issue by rdudacz** [rails/sass-rails#131]
Hello guys,

I am trying to use in my app new font with using the `@font-face`, but the app still cannot load them.

I use following setup:
## application.rb

config.assets.paths << "#{Rails.root}/app/assets/fonts"
config.assets.precompile += %w(*.svg *.eot *.ttf *.woff)
## app.css.scss

@font-face {
  font-family: 'my_font';
  src: font-url('Androgyne_TB.eot'); 
  src: font-url('Androgyne_TB.eot?#iefix') format('embedded-opentype'), 
         font-url('Androgyne_TB.woff') format('woff'), 
     font-url('Androgyne_TB.ttf')  format('truetype'), 
     font-url('Androgyne_TB.svg#AndrogyneMedium') format('svg');  
}

The fonts are stored in `app/assets/fonts`.

When I run the app and take a look at the `app.css.scss`, there is printed out this path to the fonts: `src: url(/assets/Androgyne_TB.eot);` etc. and when I put this URL into browser, then is this font offered my for download -> which looks the path is okay.

But the main problem - the font is still not displayed in my app.

Didn't has anyone the same problem and could help me with?

Thanks
(and I am sorry if I put this issue into the bad issue-channel)

**Comment by hendricius** [comment]
Old ticket - but I am having the same issue.

My work-around here is the following:

```
@font-face {
    font-family: 'San Francisco Display';
    src: url(font-path('san-francisco/sanfranciscodisplay-bold-webfont.eot'));
    src: url(font-path('san-francisco/sanfranciscodisplay-bold-webfont.eot?#iefix')) format('embedded-opentype'),
         url(font-path('san-francisco/sanfranciscodisplay-bold-webfont.woff2')) format('woff2'),
         url(font-path('san-francisco/sanfranciscodisplay-bold-webfont.woff')) format('woff'),
         url(font-path('san-francisco/sanfranciscodisplay-bold-webfont.ttf')) format('truetype'),
         url(font-path('san-francisco/sanfranciscodisplay-bold-webfont.svg#San Francisco Display bold')) format('svg');
    font-weight: 700;
    font-style: normal;
}
```

It seems you need to use `'` or `"` around the urls of your font files. Else it will not work. 

So this final CSS is valid:

```
@font-face {
  font-family: 'San Francisco Display';
  src: url("/assets/san-francisco/sanfranciscodisplay-semibold-webfont.eot");
  src: url("/assets/san-francisco/sanfranciscodisplay-semibold-webfont.eot?#iefix") format("embedded-opentype"), url("/assets/san-francisco/sanfranciscodisplay-semibold-webfont.woff2") format("woff2"), url("/assets/san-francisco/sanfranciscodisplay-semibold-webfont.woff") format("woff"), url("/assets/san-francisco/sanfranciscodisplay-semibold-webfont.ttf") format("truetype"), url("/assets/san-francisco/sanfranciscodisplay-semibold-webfont.svg#San Francisco Display semibold") format("svg");
  font-weight: 600;
  font-style: normal;
}
```

Whereas this CSS here is invalid:

```
@font-face {
  font-family: 'San Francisco Display';
  src: url(/assets/san-francisco/sanfranciscodisplay-semibold-webfont.eot);
  src: url(/assets/san-francisco/sanfranciscodisplay-semibold-webfont.eot?#iefix) format("embedded-opentype"), url(/assets/san-francisco/sanfranciscodisplay-semibold-webfont.woff2) format("woff2"), url(/assets/san-francisco/sanfranciscodisplay-semibold-webfont.woff) format("woff"), url(/assets/san-francisco/sanfranciscodisplay-semibold-webfont.ttf) format("truetype"), url(/assets/san-francisco/sanfranciscodisplay-semibold-webfont.svg#San Francisco Display semibold) format("svg");
  font-weight: 600;
  font-style: normal;
}
```

I also validated this here:
https://jigsaw.w3.org/css-validator/validator

If real issue - please let me know. I will create a pull request.

**Comment by gregblass** [comment]
I think this may still be a bug. I am pretty sure it is being caused by your dropping of .css.scss. As soon as I did this, font-url doesn't work in production. font-url is widely accepted as the way to load fonts in the asset pipeline across stackoverflow. Spent a good deal of time tracking this down.

I would revisit this if you guys insist on dropping the css.scss - I'm almost positive that broke font-url.

Anyway, the convention above does work as a workaround for now, so thank you @hendricius :

url(font-path( ))

Got the css.scss warnings after using @import instead if //= requires. //= requires was giving me problems all the time with compilation times due to caching bugs (sprockets?)
