### ISSUE TITLE
sass-rails couldn't delete `Sass::Plugin::Rack`

### ISSUE THREAD

**Issue by tricknotes** [rails/sass-rails#136]
When `Sass::Plugin::Rack` is defined, sass-rails [try to delete](https://github.com/rails/sass-rails/blob/v4.0.0.beta1/lib/sass/rails/railtie.rb#L33) this middleware.
But middlewares are frozen in rails(4.0.0.beta1) and raise the following error:

```
can't modify frozen Array (RuntimeError)
```

**Comment by justin808** [comment]
Was this ever resolved? I'm hitting this one.

**Comment by rafaelfranca** [comment]
Could you create a sample application reproducing it?

**Comment by justin808** [comment]
I don't think so. I'm upgrading a giant old rails project to Rails 4 with many old gems.

Any tip on how to trace down where this error is coming from:

   RuntimeError:
       can't modify frozen Array

The stack trace only tells me it's coming from my sass file.

**Comment by mjtko** [comment]
@justin808 

In case it helps, here's how I've been working around this issue in an initializer:

```
  # mjt - if it has been added for any reason, remove badly added
  # Sass::Plugin::Rack middleware now, before it all falls apart in
  # sass-rails (see https://github.com/rails/sass-rails/issues/136)
  if defined?(Sass::Plugin::Rack)
    app.config.middleware.delete(Sass::Plugin::Rack)
  end
```

**Comment by rafaelfranca** [comment]
So PDI, you are in the best position to fix this issue for everyone since you are able to reproduce and with this find the cause and fix it.

**Comment by daqo** [comment]
In case still anyone faces the problem, try to use ```config.app_middleware.use```.
https://stackoverflow.com/questions/34444757/controlling-rails-initializer-load-order-possible-need-for-new-rails-initializa
