### ISSUE TITLE
rake assets:precompile fails on production

### ISSUE THREAD

**Issue by charleskirk** [rails/sass-rails#158]
We've been struggling with this one for almost a day. 

We're using a theme from wrap bootstrap, which uses SCSS. It compiles absolutely fine on development, but on production it just doesn't play ball.

I'm really lost on where to get help on this one from, any assistance would be greatly appreciated.

Here's some of my code: https://gist.github.com/charleskirk/5555615
- let me know if anything else is needed.

Here's the error and stack trace:

```
localhost:assets charleskirk$ /Users/charleskirk/.rvm/rubies/ruby-1.9.3-p286/bin/ruby /Users/charleskirk/.rvm/gems/ruby-1.9.3-p286/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
(in /Users/charleskirk/jvo-portal)
rake aborted!
Invalid CSS after "&.": expected class name, was "#000"
  (in /Users/charleskirk/jvo-portal/app/assets/stylesheets/action_nav.css.scss)
/Users/charleskirk/jvo-portal/app/assets/stylesheets/action_nav.css.scss:104
/Users/charleskirk/.rvm/gems/ruby-1.9.3-p286/gems/sass-3.2.8/lib/sass/scss/parser.rb:1148:in `expected'
/Users/charleskirk/.rvm/gems/ruby-1.9.3-p286/gems/sass-3.2.8/lib/sass/scss/parser.rb:1084:in `expected'
/Users/charleskirk/.rvm/gems/ruby-1.9.3-p286/gems/sass-3.2.8/lib/sass/scss/parser.rb:1066:in `expr!'
```

**Comment by bluedreamR** [comment]
I deployed rails project on Amazon EC2.
but I found below issue
`Precompiling asset files
       rake aborted!
       Sass::SyntaxError: Undefined variable: "$body-background".`

finally,
`/home/ec2-user/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
       /home/ec2-user/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
       /home/ec2-user/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
       /home/ec2-user/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !     ERROR: Deploy failed.
-----> Cleaning up build
       Unlinking current
       OK
       Connection to (server_ip_address) closed.

 !     Run Error`
help me!
I can't deploy my new version of this project on production because this issue.
