### ISSUE TITLE
image-data-url not picking up images that image-url does

### ISSUE THREAD

**Issue by artsyca** [rails/sass-rails#164]
Hello, my apologies in advance if this is an issue with my local setup rather than sass-rails. However, nothing I can think of seems to work.

I am working in a mountable engine trying to load some assets from another engine, connected as a gem.

When I use `image-url` the asset path is correctly resolved, whereas an identical call to `image-data-url` will not be resolved and that code is output in the CSS as-is (i.e. no converted to a `url(data:...)` declaration.

So for example:

```
image-url("icons/icon.svg")
```

Will be output correctly as:

```
url(path/to/icons/icon.svg)
```

The same call to `image-data-url` will not:

```
image-data-url("icons/icon.svg")
```

Is output as-is (in CSS):

```
image-data-url("icons/icon.svg")
```

And shows up in the inspector as an invalid rule. Expected behaviour would be `url(data:base64 encoded icons/icon.svg)`

Any help on this issue is greatly appreciated. This is Rails 4 with Ruby 1.9.3

(Also, same goes for asset-data-url)

**Comment by hovissimo** [comment]
This is the top Google result for me.  Can you please describe the problem and the fix in more detail?
