### ISSUE TITLE
Overwrite SASS engine partials  in application

### ISSUE THREAD

**Issue by leomao10** [rails/sass-rails#166]
Given an engine like the following

``` ruby
module Foo
  class Engine < ::Rails::Engine
  end
end
```

And the folder structure like this:

```
stylesheets
  globals
    _variables.css.scss
    _pie.css.scss
  _global.css.scss
```

`_global.css.scss` looks like this:

``` scss
@import 'globals/variables';
```

And `globals/variables` is empty in engine.

In my application, I have folder structure like this:

```
stylesheets
  globals
    _variables.css.scss
```

In my application.css.scss will import `global` scss in the engine:

``` scss
@import 'global';
```

And I have a `globals/variables` in my application that have following code:

``` scss
$invalid-background-color:#FEF1EC;
$invalid-border-color:red; 
```

And I want to let `_variables.css.scss` in my application override the one in my engine, just like the way rails does in view folder.

But I found that I don't have `$invalid-background-color` define in my `application.css.scss`, and I did a bit of debugging for the code and found that sass-rails actually import the `global/variable` file in the engine, not the one in the application. 

And I think it is because when evaluate `global` partial in the engine, [importer.rb#engine_from_path](https://github.com/rails/sass-rails/blob/v4.0.0/lib/sass/rails/importer.rb#L66) will change it is context to the path of `global` partial in [here](https://github.com/rails/sass-rails/blob/v4.0.0/lib/sass/rails/importer.rb#L77). And @import for the file will use the closest `variable` file relative to `global` partial, which is the one in the engine.

Is this the intended behavior for `sass-rails` or I am just doing something stupid?

**Comment by stevehanson** [comment]
I'm having the same issue: creating a partial in my app is not overriding the partial from my engine with the same path and filename.

Any progress on this, or does anyone have a fix for it?

**Comment by 01010000101001100** [comment]
+1
