### ISSUE TITLE
asset-url not working in Rails 4

### ISSUE THREAD

**Issue by ghost** [rails/sass-rails#169]
Hi,

I cannot figure out what I am doing wrong here.  I am using asset-url with the font declaration in a .scss file and when I compile to .css, nothing changes.  The asset-url isn't being parsed.  I am hoping this helper picks up the MD5 fingerprint on a production compile as well, but I haven't gotten that far yet.

@font-face {
  font-family: 'FontAwesome';
  src: asset-url("fontawesome-webfont.eot", font);
  src: asset-url("fontawesome-webfont.eot", font) format('embedded-opentype'),
    asset-url("fontawesome-webfont.woff", font) format('woff'),
    asset-url("fontawesome-webfont.ttf", font) format('truetype'),
    asset-url("fontawesome-webfont.svg", font) format('svg');
//  src: url('#{$FontAwesomePath}/FontAwesome.otf') format('opentype'); // used when developing fonts
  font-weight: normal;
  font-style: normal;
}

Becomes:
@font-face{font-family:'FontAwesome';src:asset-url("fontawesome-webfont.eot", font);src:asset-url("fontawesome-webfont.eot", font)

Thanks.

**Comment by ryannealmes** [comment]
Ping me any time :)

**Comment by Ajaxy** [comment]
Same issue, nothing helps :(

**Comment by hangmiao** [comment]
I run into the exact same problem:
Inside the `public/assets/application-*.css`, it refers to *non-digest* file names while the files in `public/assets/fonts` are all with *digest* file names. So the sever couldn't find it.

To solve it:
1. Change the css file to css.scss file (it was a css file before)
2. Change `src: url` to `src: asset-url` and other places correspondingly
3. Enable `config.assets.css_compressor = :sass` in `production.rb` as @Eptis mentioned

The `public/assets/application-*.css` now refers to *digest* file names.
:smile:
