### ISSUE TITLE
Error when importing .css.scss.erb stylesheet by wildcard

### ISSUE THREAD

**Issue by andreychernih** [rails/sass-rails#185]
I have `active_admin.css.scss` file which imports all stylesheets in `active_admin` directory:

```scss
@import "active_admin/*";
```

When I put `sample.css.scss.erb` file into this dir, it fails to import with error:

```
File to import not found or unreadable: active_admin/sample.css.scss.erb.
```

However, if I import this file by it's name, everything works just fine:

```scss
@import "active_admin/sample";
```

Possibly related to https://github.com/rails/sass-rails/issues/139

**Comment by francesco-carrella** [comment]
+1

**Comment by lifeiscontent** [comment]
@chriseppstein any updates on this?

**Comment by filp** [comment]
Poke - issue still present. Any updates/ideas?

**Comment by jaswinder97** [comment]
Still getting errors with sass-rails (5.0.6) and Rails 4.1 using import by wildcard.

@import "application_css/**/*";

Error:

File to import not found or unreadable: /mypp/app/assets/stylesheets/application_css/font-awesome.css.erb.
