### ISSUE TITLE
Glob Importing Doesn't Ignore Editor Files

### ISSUE THREAD

**Issue by jfeaver** [rails/sass-rails#186]
While using the vim text editor and using glob importing, I get compilation errors whenever I edit files.  These errors are caused by the glob importer attempting to import the vim backup files ending in `~`, such as `application.css.scss~`.

This could be the case with other editor-specific files but I haven't tested.

**Comment by javiguajardo** [comment]
Hi there, has this issue been fixed?

**Comment by jfeaver** [comment]
Hey @javiguajardo. It looks to me like these lines are glob matching filenames and the `$` in the compiled `Regexp` will prevent files ending in `~` from being imported.

https://github.com/rails/sass-rails/blob/master/lib/sass/rails/importer.rb#L48-L49
