### ISSUE TITLE
Update sprockets dependency

### ISSUE THREAD

**Issue by connorwarnock** [rails/sass-rails#207]
A number of gems have moved on to sprokets 2.12.0, so capping the gem at 2.11.0 is causing dependency issues.

phyllisstein seems to have it patched here: https://github.com/phyllisstein/sass-rails/commit/36524cf168e7e31b072b71b8282e75c5652da3d3

**Comment by bradgreens** [comment]
+1 @raulsann for `gem install bundler && bundle install`
