### ISSUE TITLE
Issue with maps?

### ISSUE THREAD

**Issue by rafaelrinaldi** [rails/sass-rails#215]
I was working on a project running the Node.js version of Sass then I moved my libraries to a Ruby project that is using this gem to compile Sass. I had an issue with one of my files that uses the object map feature to config some styles. Something like the following:

``` sass
$conf: (
  'background-color': #ff0066,
  text: #fff
);

body {
  background: map-get($conf, 'background-color');
  color: map-get($conf, 'text');
}
```

I get the following error:

```
Invalid CSS after "...ckground-color'": expected ")", was ": #ff0066,"
```

The thing is I was using this library without an issue until now.
Any ideas on what's going on?

**Comment by ptrikutam** [comment]
I had the same issue, @rafaelrinaldi -- what did you do to fix this?

Did you just stop using Sass maps? I know that the version required for `sass-rails` both 4.x and 5.x lock `sass` to 3.2.x.
