### ISSUE TITLE
Rails 4 image_tag doesn't work on heroku

### ISSUE THREAD

**Issue by ghost** [rails/sass-rails#228]
I have a ruby on rails 4 app. In my app/views/static_pages/home.html.erb I have an image tag which displays a logo when I run it locally on my own computer:

```
<%= image_tag "logo.png", width: "250px", height: "90px" %>
```

but when I run the code on heroku the image is missing. I tried all different kinds of solutions posted on the web, but found only two solutions. First using

```
config.assets.compile = true
```

which is not a good solution because it uses more memory and performs more poorly. Second using

```
<img src="<%= asset_path('logo.png') %>" width="250px" height="90px">
```

which sometimes work, but sometimes doesn't. Why is this happening? Is there a way to get the <%= image_tag ... %> working on heroku?

Thanks.

**Comment by dimanyc** [comment]
@rostaamm were you ever able to resolve this?

**Comment by EvanPHamilton** [comment]
Would love to know myself

**Comment by BigBrothersBrother** [comment]
Having the same issue and haven't found a solution after hours of research...
