### ISSUE TITLE
@import from gem included assets does not cause digest to get updated

### ISSUE THREAD

**Issue by DanielNill** [rails/sass-rails#250]
If i have a sass file of the form

```sass
@import some_file_from_a_gem
// the rest of my sass ....
```
When a change is made to that imported file, sass-rails and sprockets-rails 2.0.2 will not pick up the changes and generate the file with a new digest.

This is not reproducible for files in `app/assets/stylesheets/...`

This issue exists on sass-rails 4.0.3.  Downgrading to 4.0.2 resolves the problem.

broken gemfile.lock dependency tree:
```
sass-rails (4.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.0)
      sprockets (~> 2.8, <= 2.11.0)
      sprockets-rails (~> 2.0)
```
working gemfile.lock dependency tree:
```
sass-rails (4.0.2)
       railties (>= 4.0.0, < 5.0)
       sass (~> 3.2.0)
       sprockets (~> 2.8, <= 2.11.0)
       sprockets-rails (~> 2.0.0)
```

**Comment by eguitarz** [comment]
+1

My sass-rails is 5.0.1, sprockets-rails is 2.2.2
When I modify the imported file in application.css.scss, it won't recompile.

**Comment by rafaelfranca** [comment]
Are you using compass-rails?

**Comment by eguitarz** [comment]
Yes, my compass-rails is 2.0.1

**Comment by rafaelfranca** [comment]
compass-rails is know to have incompatibility with sass-rails 5. See https://github.com/Compass/compass-rails/pull/201

**Comment by DanielNill** [comment]
haven't tried this with 5 yet but I reproduced with without using compass-rails.

**Comment by rafaelfranca** [comment]
Please try with the 5 version

**Comment by kylerippey** [comment]
I've reproduced this issue using sass-rails 5.0.3 in a fresh rails 4.2.1 app. The app is not using compass-rails. Example and repro steps can be found here: https://github.com/kylerippey/sass_rails_issue

**Comment by kylerippey** [comment]
Okay, after digging into this for a few hours I'm fairly certain that this is actually a sprockets issue. I'm able to completely take `sass-rails` out of the mix and repro the problem. When you update a gem, sprockets appears to still look at the old gem path to determine whether or not recompilation is necessary. You can close this issue and I'll go raise the question in `rails/sprockets`.

**Comment by DanielNill** [comment]
@kylerippey please link to any issues in https://github.com/rails/sprockets you create for future reference.

**Comment by kylerippey** [comment]
@DanielNill So, I just installed sprockets-3.0.0.rc1 and found that the issue has been resolved!
