### ISSUE TITLE
ActionView::Template::Error: wrong number of arguments (3 for 1..2)

### ISSUE THREAD

**Issue by Davidslv** [rails/sass-rails#253]
Hi,

I'm trying to update rails from 3.2.18 to 4.0.9 and I'm receiving that error message lots of times, I have no idea what to do to fix it as you can see there is nothing non-trivial in application.html.erb, the same happens to other tag helpers like image_tag.

I created a gist with the only information I have, it seems it ends up being something in between of `sass-rails` and `sass`, not sure though.

https://gist.github.com/Davidslv/862c57b5490d2576e19a

Thank you for your help!

**Comment by cirdes** [comment]
+1 @philipgiuliani

**Comment by chitrank-samaiya** [comment]
+1 it helped.

**Comment by elitenomad** [comment]
:+1: 3.2.19 -sass version helps me....Thanks guys

**Comment by elchingon** [comment]
saved me. excellent - thank you!
