### ISSUE TITLE
Stylesheet does not recompile when asset image changed

### ISSUE THREAD

**Issue by timurkhafizov** [rails/sass-rails#260]
Hello!
I opened similar issue here sstephenson/sprockets#650, but was noticed that it should be `sass-rails` issue.
The problem is that I can't get main stylesheet recompile when asset image changed.
I tried to use `depend_on_asset` sprockets directive but it was said I should not use it if I use `image-url` helper.

Here are my stylesheet files:
`application.scss`:
```scss
@import "bootstrap";
@import "theme/theme";
```
`theme/_theme.scss`:
```scss
@import "modules/main";
@import "modules/header";
@import "modules/footer";
```
and `modules/_footer.scss`:
```scss
footer {
  a.logo {
    background: #fff image-url('logo_footer.png') 50% 50% no-repeat;
  }
}
```
Unfortunately rake assets:precompile does not recompile main stylesheet file, but creates new logo_footer.png asset. Assuming I have precompiled assets:
```bash
$ mv ~/new_logo_footer.png app/assets/images/logo_footer.png
$ rake assets:precompile
I, [2014-10-20T14:22:30.395039 #48997]  INFO -- : Writing /Users/timurkh/my_project/public/assets/logo_footer-6dcc4e9b43cc0bf41076c7981ab96d16.png
```
I can not understand why it doesn't work.
Please advise if there is any ability to get my stylesheet to recompile properly.

I use:
```ruby
sprockets (2.11.0)
sprockets-rails (2.0.1)
sass-rails (4.0.1)
```
Thank you!

**Comment by joassouza** [comment]
Have you tried change to asset_url?

**Comment by rafaelfranca** [comment]
More than three months without feedback so I'm closing. Thank you for reporting.
