### ISSUE TITLE
SASS 3.4.7 working?

### ISSUE THREAD

**Issue by gespinha** [rails/sass-rails#267]
Hi there,

Do you have support for SASS 3.4.7 (or 3.4) planned in the near future?

I am trying to run it with sass-rails, but because of the dependancy on an older version of SASS, this doesn't work.

Thanks in advance!

**Comment by josephwegner** [comment]
Hmm, I'm having trouble getting `@import`s to work without sass-rails.. What is the status of getting SASS 3.4.x support?

It seems [like the tests are passing](https://github.com/rails/sass-rails/pull/289) - does that mean a 3.4 compatible release is coming up?

**Comment by josh** [comment]
sass-rails 5.x should be compatible with sass 3.4

**Comment by josephwegner** [comment]
boy, I feel like a dunce. I swear I was getting bundler errors because of dependency conflicts this morning…  but it works now!




Thanks!


—
