### ISSUE TITLE
Not importing .css.scss extensions

### ISSUE THREAD

**Issue by pusewicz** [rails/sass-rails#290]
Hi!

There is a problem with current implementation of the Importer with the combination of Sass 3.4.9.

``` scss
@import 'active_admin/mixins';
```

Throws an error, saying that it cannot find a file. The file in the gem has `.css.scss` extension.

Now Changing https://github.com/rails/sass-rails/blob/master/lib/sass/rails/importer.rb#L108 to include 

``` ruby
{ 'css' => :scss, 'css.scss' => :scss }
```

fixes the problem.

**Comment by jmcnevin** [comment]
Could someone point me to the relevant sprockets discussion that made this deprecation necessary?

**Comment by ahnbizcad** [comment]
Are there any config settings that need to change along with this?

I renamed all my .css.scss files to .scss, but I'm consistently getting 


ExecJS::ProgramError at /

TypeError: Object doesn't support this property or method (in c:/Sites/gwhosaidthat/app/assets/stylesheets/application.scss)

I've tried making application.scss a blank file with no text, but still it give the error.

**Comment by jaredbeck** [comment]
>>> Then if we want to properly kill them off, we can phase in a more active deprecation later.
>>
>> They will be completely unsupported in Sprockets 4.x. Which is why they're now soft deprecated in 3.x
>
> Could someone point me to the relevant sprockets discussion that made this deprecation necessary?

- The commit that drops support:
https://github.com/sstephenson/sprockets/commit/da2f1d176de6fae0bafc71e9cbf7805271856933
- Announcement, sprockets 3.0: https://github.com/sstephenson/sprockets/issues/643
- Discussion, sprockets 4.0: https://github.com/sstephenson/sprockets/pull/632
