### ISSUE TITLE
Does not show Rails error page when using wildcard @import

### ISSUE THREAD

**Issue by envygeeks** [rails/sass-rails#309]
In our app when we do `@import "bundle/*";` of partials we do not see errors, but we do see them when we include each one of those files individually.

**Comment by rafaelfranca** [comment]
Which error? You need to provide more information if you want this issue to be fixed.

**Comment by envygeeks** [comment]
Even though I wasn't broad I'll give you an example so you can replicate it and see for yourself.
It's easy to replicate (we use Ruby 2.1 and Rails 4.2)


```
// app/assets/stylesheets/bundle/_test.scss
$var-doesnt-exist
```

```
// app/assets/stylesheets/application.scss
@import "bundle/*"
```

Load Rails in dev and watch the app fall down but there be no Rails error page, instead you have to go to the terminal to see the Sass error but if you switch it to include the partial directly you do see the error.
