### ISSUE TITLE
adding sass-rails features to scss-lint

### ISSUE THREAD

**Issue by digitalvapor** [rails/sass-rails#310]
Do any of you know how to implement a [scss-lint](https://github.com/causes/scss-lint) linting rule to use the sass-rails [features](https://github.com/rails/sass-rails#features)?

Thanks in advance

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
