### ISSUE TITLE
Is it possible to enable SOURCEMAPS for debugging?

### ISSUE THREAD

**Issue by rocketonrails** [rails/sass-rails#313]
I spent quite some hours trying to figure out this, is it possible? I used several flags and none of them seems to override the default mechanism of CSS concatenation of Rails.

**Comment by gkatsanos** [comment]
+1

**Comment by andreyors** [comment]
+1

**Comment by rafaelfranca** [comment]
See https://github.com/rails/sass-rails/issues/314#issuecomment-75968784
