### ISSUE TITLE
Does the config.sass.sourcemap option work?

### ISSUE THREAD

**Issue by gkatsanos** [rails/sass-rails#314]
Does the config.sass.sourcemap option work? I tried it but had no result whatsoever. 
Since SASS generates maps by default, why isn't it generating them with this gem?

**Comment by rafaelfranca** [comment]
No. The current version of sprockets (2.x) doesn't support source maps. The 3.x version also doesn't support but it will be supported with the 4.x version that will be released this year.

**Comment by gkatsanos** [comment]
Thanks, I just saw this https://github.com/rails/sass-rails/issues/314#issuecomment-75968784
