### ISSUE TITLE
@import is not finding the files in nested folders properly

### ISSUE THREAD

**Issue by pencilcheck** [rails/sass-rails#320]
If include both gems in Gemfile

```
gem 'bourbon'
gem 'rails-assets-card', '~> 1.0.0'
```

And then in `application.css.scss` add lines

```
/*
 *= require card
*/
@import "bourbon";
```

or

```
@import "card";
```

Result an error when trying to load a page

```
File to import not found or unreadable: bourbon/app/assets/stylesheets/bourbon.
Load paths:
  /Users/penn/Projects/workties/web/app/assets/images
  /Users/penn/Projects/workties/web/app/assets/javascripts
  /Users/penn/Projects/workties/web/app/assets/stylesheets
```

It seems like it is caused by the file `https://github.com/jessepollak/card/blob/master/src/scss/card.scss` that it imports from the bourbon they included in the library's scss folder.

To give some context: rails-assets converts a bower library into asset pipeline compatible gems so in `jessepollak/card` case the scss folders are included into asset pipeline when included as 'rails-assets-card' gem.

The problem seems to be on sass side since the expected behavior should be passing but somehow it is not the case...

Links:

```
https://github.com/jessepollak/card
https://github.com/thoughtbot/bourbon
```

**Comment by dwoowb** [comment]
@pencilcheck did you ever find a resolution to this issue?
