### ISSUE TITLE
Different precompiled files with same code

### ISSUE THREAD

**Issue by agrass** [rails/sass-rails#321]
When I precompile the same css in two servers I get differents css minimized. I don't know the reason of this issue,I have the same config (config.assets.css_compressor = :sass)

For example one part of the unpacked minimized css in server 1 is like this (the same that the real file) :
<pre><code>
.c3-tooltip
{
    border-collapse:collapse;
    border-spacing:0;
    background-color:#fff;
    empty-cells:show;
   <strong> -webkit-box-shadow:7px 7px 12px -9px #777;
    -moz-box-shadow:7px 7px 12px -9px #777;
    box-shadow:7px 7px 12px -9px #777; </strong>
    opacity:0.9
}
</pre></code>
Then in server 2 I get this (webkit-box-shadow and -moz-box-shadow were removed):
<pre><code>
.c3-tooltip
{
    border-collapse:collapse;
    border-spacing:0;
    background-color:#fff;
    empty-cells:show;
    box-shadow:7px 7px 12px -9px #777;
    opacity:0.9
}
</pre></code>

**Comment by arthurnn** [comment]
how are you getting that info?
Are you doing curl calls to 2 different servers and seeing different results?
Not sure how to simulate this issue, if you could provide a sample app would help out.
thanks

**Comment by agrass** [comment]
I have a loadbalancer with different servers and sometimes the stylesheets are were not loaded. I checked the names of the css compressed files and in one server I have a different fingerprint. Next uncompressing the files with (http://cssunpacker.com/) I realize that one of the servers when compress the css is removing some -webkit, -moz  and other syntaxis.

**Comment by rafaelfranca** [comment]
> one server I have a different fingerprint

This means that the file content is not the same. Something is generating different files in your server.

If the code is the same and the version of the gems are the same I don't see why sprockets would generate different results. Make sure that your assets folders and dependencies are the same.

**Comment by agrass** [comment]
Yes, the compressed file in one server remove some lines as shown in the first comment. I just realize that most of the files that have this problem have ".css.scss" extension and files with .sass extension don't have this problem. Could be something related with this? I know that in the latest version of sass-rails the .css.scss extension is deprecated.

**Comment by rafaelfranca** [comment]
Don't think so. Given the same environment and the same code, I don't see how the files would be different. I'd make sure that the environment is the same in both servers first (gem versions, dependencies versions, assets code)

**Comment by agrass** [comment]
It's the same code and gem versions. The deploy in both servers use the same branch. In the server with the problem if I check the non precompiled assets It's exactly the same of the other server, but when I compress it, some attributes as shown in the first comment were removed.

**Comment by rafaelfranca** [comment]
Does that code being generated by some gem like compass or bourbon? Seems only the prefix styles are missing, but the box-shadow is there.

**Comment by agrass** [comment]
No, the only difference are that in the server of the problem I'm using AWS opsworks with some chef recipes and I don't have rbenv configured, It's possible that some of this is cousing this issue? (I use the default recipes of opsworks rails layer). The box-shadow is there in both servers, the compression remove the whole line "-webkit-box-shadow" and "-moz-box-shadow".Thanks, I would really appreciate any help or comments about this issue.

**Comment by rafaelfranca** [comment]
> `"-webkit-box-shadow" and "-moz-box-shadow"`

In our sass code are these properties generated by some kind of mixin?

Like:

```
@include box-shadow(7px 7px 12px -9px #777);
```

Not having rbenv configured can be a reason for this yeah, if that means that global gems installed on the machine are affecting your application, but I'd guess bundler would protect you.

**Comment by agrass** [comment]
not, It's not generated by some kind of mixin, they are in some imports of scss from the application.sass with normal css syntax.

**Comment by rafaelfranca** [comment]
:confounded: so this is now even more weird. If it is just normal css syntax I can't see how this same file can be different in different servers.

**Comment by agrass** [comment]
yes is very weird. Finally I give up with this issue and decided to use the gem 'asset_sync' to upload the assets on s3.

**Comment by Fudoshiki** [comment]
RAILS_ENV=production rake assets:precompile on server dropped 

```
  font-family: "ヒラギノ丸ゴ ProN W4", "Hiragino Maru Gothic Pro", "メイリオ", Meiryo, Helvetica, sans-serif
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0)
  -ms-text-size-adjust: 100%
  -webkit-text-size-adjust: 100%
```
from html section

on local machine not

**Comment by ekaitzht** [comment]
The same is happening to me  my css vendor prefixes are removing in production enviroment but not in my local machine. Here you can get more info http://stackoverflow.com/questions/32179803/rails-removing-css-vendor-prefixes-in-production-enviroment
