### ISSUE TITLE
SASS cache location

### ISSUE THREAD

**Issue by oslyak** [rails/sass-rails#322]
I have standard Rails 4.2 app, without compass.

I found similar question but with compass usage.

Recently in the project directory appears folder ".sass-cache".
All what i want , it's just move it to tmp.

In application.rb tried:

    module Sirius41
      class Application < Rails::Application
        ...
        config.sass.cache_location = Rails.root.join('tmp', '.sass-cache').to_s
        ap config.sass
      end
    end
    
    sass_options = {:cache_path => Rails.root.join('tmp', '.sass-cache').to_s}

But it don't change the cache location.

Rails sass config values:

    {
     :preferred_syntax => :scss,
       :cache => true,
       :read_cache => true,
       :line_comments => true,
       :load_paths => [],
       :logger => #<Sass::Rails::Logger:0x007f80d9148118     @log_level=:debug>,
       :cache_location => "/home/anton/rubyprojects/sirius42/tmp/.sass-cache"
    }

**Comment by rafaelfranca** [comment]
Are you sure that this directory is being create by sass-rails? By the default configuration and the fact that any of my projects have this folder I think it is something else that is creating. Could you create an example application that reproduces it?

**Comment by oslyak** [comment]
I created new project with only one additional gem 'haml'.
And added one partial 
/app/views/layouts/_material_circle.html.haml
Inside haml template there is scss.
This is file is the reason of creation ".sass-cache"

https://github.com/oslyak/sass-test

**Comment by rafaelfranca** [comment]
I see. This seems to be related with `haml`. Is you able to reproduce it with ERB?

**Comment by oslyak** [comment]
No, I don't

**Comment by rafaelfranca** [comment]
I see. Maybe you should open an issue on the haml repository since it is specific for haml.

Thank you for reporting.
