### ISSUE TITLE
.sass media query won't precompile

### ISSUE THREAD

**Issue by nitsujri** [rails/sass-rails#325]
Not sure if this is the right place.

Simple `responsive.sass`:

    // Anything smaller than XS
    @media(max-width:767px)

    //Anything larget than SM
    @media(min-width:768px)

    // Anything smaller than MD
    @media(max-width:991px)
      body
        padding-bottom: 566px

    // Anyting larger than MD
    @media(min-width:992px)

    @media(min-width:1200px)

Running `rake assets:precompile` it complains:

    Sass::SyntaxError: Invalid CSS after "...ax-width:767px)": expected "{", was ";"
      (in /Users/nitsujri/ruby/testproj/app/assets/stylesheets/application.sass)
    (sass):12350

If I 

1. Change the file to `responsive.scss` 
1. Put the brackets in
1. Run precompile

It works as expected.

**Comment by rafaelfranca** [comment]
Are you able to make it work without Rails?

**Comment by nitsujri** [comment]
@rafaelfranca, I'm not sure how to do that. Could you point me? Gladly run the test.

**Comment by rafaelfranca** [comment]
Try:

```
gem install sass
sass responsive.sass
```

**Comment by nitsujri** [comment]
Ugh, I kept working on the project and the problem doesn't reproduce, of course. Thanks for the time and all that you do, @rafaelfranca.
