### ISSUE TITLE
Latest sass-rails requires the file extension to be specified when using @import.

### ISSUE THREAD

**Issue by gabrielecirulli** [rails/sass-rails#332]
I recently noticed that I was still using `5.0.0.beta1`, and I've now updated to `5.0.3`. I noticed that one of the behaviours I used to depend on changed since then.

In my `application.css.scss` I had the following line

```scss
@import "guidelines";
```

This refers to a file in the same directory called `guidelines.css.scss`. Since updating, I started getting "File to import not found or unreadable". I noticed that by replacing my line with 

```scss
@import "guidelines.css.scss";
```

it works again. Is this supposed to happen, or could it be a regression? If it's supposed to be like this, then no worries, I'll just fix my code. I just wanted to ask to make sure!

**Comment by gabrielecirulli** [comment]
Here's a diff of my Gemfile.lock once I changed the dependencies: https://gist.github.com/gabrielecirulli/4049159cb1784b4005c7 (probably includes some unrelated entries)

**Comment by gabrielecirulli** [comment]
I also seem to be unable to implement a file called `variables/components.css.scss.erb`, which I was able to import previously just by saying `variables/components`.

**Comment by rafaelfranca** [comment]
Does a file named `guidelines.scss` works?

**Comment by bolandrm** [comment]
Just reproduced.  Looks like `sass-rails-source-maps` is causing this issue.

**Comment by rafaelfranca** [comment]
Right. So we should move this issue to their repository. @gabrielecirulli could you open an issue there? Thanks
