### ISSUE TITLE
Unending stream of error messages

### ISSUE THREAD

**Issue by jxxcarlson** [rails/sass-rails#335]
I had been using
   ruby '2.1.2'
   gem 'rails', '4.0.0'
   gem 'sass-rails', '~> 4.0.0'
but was getting long streams of warining that include "instance variable not initialized'  Tonight I upgraded
to 

ruby '2.2.2'
gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0.3'

and the situation is far worse. The error stream went on for at least 10 minutes. Here a line from thousands -- maybe tens of thousands:

remote:        /tmp/build_a296d8b3622dfcecfac341f9277cd823/vendor/bundle/ruby/2.2.0/gems/sass-3.4.15/lib/sass/tree/visitors/to_css.rb:74: warning: instance variable @lstrip not initialized

I really don't know what to do at this point.  I am reverting to previous commit.

Thanks,

Jim

**Comment by rafaelfranca** [comment]
Hi Jim, thank you for the report. The warning is coming only from the sass gem, or there is something pointing to sass-rails?

**Comment by jxxcarlson** [comment]
Ah — I see that I reported it in the wrong place.  As far as I can tell everything has the prefix gems/sass-3.2.19.

Sorry for the noise — on my way to sass.

**Comment by rafaelfranca** [comment]
No problem. Thank you again.
