### ISSUE TITLE
Glob Imports missing new files

### ISSUE THREAD

**Issue by BroiSatse** [rails/sass-rails#337]
It seems that when doing a global folder import, new files added to that folder tend to be missed during compilation. Removing `tmp/cache/assets` and restarting the server helps, however we also experienced this when deploying to heroku.

For now, the way we solve it is to make any change to a file containing global import (adding extra space), so it forces file to be recompiled. Any better way to do this?

**Comment by bolandrm** [comment]
Seems to be a duplicate of https://github.com/rails/sass-rails/issues/189
