### ISSUE TITLE
Globbing fails when files are in the vendor directory

### ISSUE THREAD

**Issue by thecristen** [rails/sass-rails#352]
(yes, it's issue #240)

My use case: I have some SASS in a subdirectory in `vendor/assets/stylesheets` and my teammates can add more files that subdirectory - therefore I need to be able to `@import "./{subdirectory}/*";` and be done. Instead it throws an error `couldn't find file '{...}/app/assets/stylesheets/{subdirectory}'`

 `@import "./{subdirectory}/{file}";` works as expected, but globbing should really be consistent for any directory in the assets pipeline.

**Comment by gauthamchandra** [comment]
I have the same issue for relative directories as well.

If you have:
```
- main.css.scss
- subfolder/
  - somefile.css.scss
  - ... a bunch more files

- subfolder2/
  - module.css.scss
```

From `main.css.scss`, `@import subfolder/*";` works perfectly for me.
But if I try to run the same import from `subfolder2/module.css.scss` I get the whole `file to import not found or unreadable`.

Manually importing each of the files individually via `@import subfolder/somefile";` works though so it has to be with the globbing logic.

**Comment by leandro** [comment]
I'm having this very same issue in them gem version 5.0.6. Any suggestions?

**Comment by leandro** [comment]
I've just opened a PR that solves this problem. I hope that someone from the staff can check this out.

For now, I targeted the fix to `5-0-stable` branch. I didn't test if it also solves the problem in version 6.

**Comment by raliste** [comment]
Any updates on this?
