### ISSUE TITLE
How do you finally use @import?

### ISSUE THREAD

**Issue by remino** [rails/sass-rails#354]
Using the simplest `@import` can be the most frustrating thing to do with `sass-rails`.

In one version, I can simply call `@import 'common/variable'`, for example, yet in the other, I must explicitly include the extension `@import 'common/variable.css.scss'`. I'd figure `sass-rails` should be smart enough to do the former, but since updating to 5.0.4 from 4.0.5, it no longer works. Somehow, it'll look for `common/_variable.css.scss` (with the underscore), but it can't figure out the file extension.

I don't care about adding the extension or not, but I'd like to know once and for all, do I need to specify it or not? Can we add that answer to the `README`?

Thanks in advance.

**Comment by aried3r** [comment]
I'm not very familiar with sass-rails, but `.css.scss` and `.css.sass` file extensions were [deprecated in 5.0.0](https://github.com/rails/sass-rails/releases/tag/v5.0.0), maybe you'll have luck using the supported ones.

**Comment by remino** [comment]
I see. Thanks for showing me this. The pattern I felt was going on for the asset file extensions was `.output_format.input_format`. But I guess someome thought since Sass partials aren't outputting files on their own, that it would be best to discard the `.css` part of those file names.
