### ISSUE TITLE
Rails 5 Sass config not being merged into engine options

### ISSUE THREAD

**Issue by agrobbin** [rails/sass-rails#358]
As part of some work to get a sprockets engine working on Rails 5, I ran into what appears to be some API drift between sprockets and sass-rails.

In sass-rails 5.0.4, a `SassTemplate` is defined that handles the actual rendering of the CSS. Part of [`evaluate`](https://github.com/rails/sass-rails/blob/v5.0.4/lib/sass/rails/template.rb#L44-L46) takes the `sass_config` and merges it in to the options that are passed to `::Sass::Engine.new`. `sass_config` is set as part of the sass-rails [`Railtie`](https://github.com/rails/sass-rails/blob/v5.0.4/lib/sass/rails/railtie.rb#L60-L63)

However, in sass-rails master, there is no `SassTemplate` as Sprockets takes care of the Sass compilation in [`SassProcessor`](https://github.com/rails/sprockets/blob/v3.5.2/lib/sprockets/sass_processor.rb), which unfortunately [doesn't merge in](https://github.com/rails/sprockets/blob/v3.5.2/lib/sprockets/sass_processor.rb#L71) the `sass_config` when initializing the `::Sass::Engine`.

I'd be happy to issue a pull request to fix this, but I'm not sure which gem should have the responsibility of making sure those options get down to the `::Sass::Engine` initialization.

**Comment by rafaelfranca** [comment]
Which kind of options you want to set in `sass_config` that needs to be passed to `Sass::Engine`?

**Comment by agrobbin** [comment]
There are a variety of Sass options that someone might want to pass along to `Sass::Engine`, but the main one is part of the default options that are passed by the sass-rails `Railtie`, [`style`](https://github.com/rails/sass-rails/blob/69839a97e43373d6d1512d4ba4c371c4f9005d01/lib/sass/rails/railtie.rb#L76).

Without that, Sass falls back to `:nested`. It also means that any arbitrary options that someone wants to pass along via `Rails.application.config.sass` are now ignored.

**Comment by rafaelfranca** [comment]
Got it. We should change the sprockets's SassProcessor initializer to accepts `sass_config` so we can inject the sass configs on it without having to subclass SassTemplate again.

**Comment by agrobbin** [comment]
:+1: happy to issue a PR to sprockets myself!

**Comment by rafaelfranca** [comment]
Cool! Please fell free to do it. I'd be happy to merge.

**Comment by agrobbin** [comment]
Thanks for the quick responses @rafaelfranca!
