### ISSUE TITLE
uninitialized constant Sprockets::SassCacheStore

### ISSUE THREAD

**Issue by ACPK** [rails/sass-rails#362]
I saw this had been previously closed and locked, though I'm experiencing this issue.  Doing the fix mentioned by going back to a version from 1.5 years ago works, but would love to find a modern solution?

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
