### ISSUE TITLE
@import css file doesn't work anymore

### ISSUE THREAD

**Issue by chamnap** [rails/sass-rails#363]
I'm using the `@import` statement with pure `.css` file with version `5.0.4` of `sass-rails` with  `2.3.3` of `sprockets-rails`. It works pretty well.

However, when i upgrade to `3.0.1` of `sprockets-rails`, it stops working:

> Sass::SyntaxError: File to import not found or unreadable: hello.

I'm not so sure, this is a problem of `sprockets-rails` or `sass-rails`.

Thanks.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by wenderjean** [comment]
I had the same error using version 5.0.0 of sass-rails, when I updated to 5.0.4 works.

**Comment by shadow-moon** [comment]
yeah, I had the same error and this issue is blocking  upgrading our rails version to 4.2.6 now :cry: 

* sass-rails 1.1.0
* sprockets-rails 3.0.4

**Comment by stepheneb** [comment]
I'm having a possibly related problem using Ruby 2.4.1 and Rails 5.1.0.rc1.

see:  https://github.com/rails/rails/issues/28628

Summary: sass @import statements in application.scss appear to be ignored, instead scss files are loaded in alphabetic order.
