### ISSUE TITLE
Cached assets become stale after Sass version changes

### ISSUE THREAD

**Issue by wjordan** [rails/sass-rails#373]
When a new version of Sass generates different content from the same source file compared to a previous version (`3.2.19` to `3.4.22` was my use-case), the cached `.css` asset remains stale and is not regenerated correctly when running `rake assets:precompile`.

See rails/sprockets#325 for a more complete description and a minimal reproducible test-case Bash script. Reopened within `sass-rails` as suggested by [comment](https://github.com/rails/sprockets/issues/325#issuecomment-228173730).

**Comment by rafaelfranca** [comment]
Awesome! Thank you for taking a stab to fix it
