### ISSUE TITLE
6.0.0 beta railties dependency

### ISSUE THREAD

**Issue by richpeck** [rails/sass-rails#376]
Any chance you could bump the `railties` dependency of the beta to `< 6`? Currently, it messes up with `Rails 5` because it will only work with `railties < 5.0`

**Comment by Blackening999** [comment]
Blocker for me as well...

**Comment by panigrah** [comment]
Another ++

**Comment by bublik** [comment]
+1

**Comment by olivierlacan** [comment]
Pretty sure this was fixed via https://github.com/rails/sass-rails/commit/acff4b407f7a74ae562966e5f481a84750f06242. 

@arthurnn Do you know why 6.0.0 is still not released?

**Comment by swrobel** [comment]
@rafaelfranca @arthurnn is this gem still being maintained?

**Comment by hasghari** [comment]
Can we get a 6.0.0 release?

**Comment by rafaelfranca** [comment]
We don't need a 6.0.0 release just yet. 5.0 is the stable release and it works with Rails 5.1. sass-rails 6.0.x depends on sprockets 4 and sprockets 4 is not stable yet so we can't release. Please use sass-rails 5.0.x unless you need sprockets 4.
