### ISSUE TITLE
The proper use of @imports 

### ISSUE THREAD

**Issue by reidcooper** [rails/sass-rails#377]
In our current project app, I hope to eventually get to cleaning up our CSS/SASS assets. As I was reviewing what we have, we have tons of @imports all over our files, i.e. some global variables are contained in an seperate file and we import that file in several other stylesheets at the top. However, in our `platform.scss` (pretty much our `application.scss`), at the top I call to @import all our global variable files. Is it necessary to @import other stylesheets at the top of each stylesheet that requires it or could I just potentially only @import those global stylesheets at the top of our `platform.scss` so I only have to import once.

A snippet from my Gemfile.lock.
```
rails (4.1.14.2)
      actionmailer (= 4.1.14.2)
      actionpack (= 4.1.14.2)
      actionview (= 4.1.14.2)
      activemodel (= 4.1.14.2)
      activerecord (= 4.1.14.2)
      activesupport (= 4.1.14.2)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.14.2)
      sprockets-rails (~> 2.0)
sass (3.4.13)
    sass-rails (5.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
```

**Comment by rafaelfranca** [comment]
This is more a sass question than an issue. Yes, it is fine to @import those global stylesheets at the top of our platform.scss so I only have to import once.

**Comment by jasonfb** [comment]
@rafaelfranca No, you must understood. It is not working as the documentation states, so that's why we filed it as an Issue and not a Question. (The only question part was if this worked this way in Rails 4.1)

We will attempt to re-create on a fresh Rails install and provide exact steps to reproduce.

**Comment by rafaelfranca** [comment]
Oh, sorry. Thank you for pointing it out.

**Comment by snitko** [comment]
I can confirm this bug.
I'll describe the bug myself once again to hopefully make it clear.

Here's my application.scss:

```
@import "mixins";
@import "header";
```

Here's my mixin.scss:

`@mixin block-width { ... }`

And, finally, header.scss

.block { @include block-width; }

When run, it gives the following error: Undefined mixin 'block-width'. Interestingly, if I add `@import "mixin";` to the top of the `mixins.scss` reload the page, then remove it and reload once again - no error is present. Only if I restart the app, it then throws the error again.

**Comment by robin850** [comment]
@snitko : Would you be able to provide a sample application that reproduces this error please ? I can't manage to reproduce that with the following steps:

~~~
$ rails new foo
$ cd foo
$ mv app/assets/stylesheets/application.css app/assets/stylesheets/application.scss
$ echo '@import "mixins";\n@import "header";' > app/assets/stylesheets/application.scss
$ echo '@mixin block-width { background: "red"; }' > app/assets/stylesheets/mixins.scss
$ echo '.block { @include block-width; }' > app/assets/stylesheets/header.scss
$ bin/rails s
~~~

Anyway, this seems strange that requiring another file fix this issue ; maybe you are just expecting that the mixin is defined in `mixins.scss` while it is defined in `mixin.scss`.

**Comment by jasonfb** [comment]
upon review we have decided this is a known-issue, in fact, there's a big "Important Note" about it at the very top of the README on this very gem. Our issues are only present when we mix the sprockets ```#= require``` with ```@import``` embedded within the included files.

we think this note explains the situation to our satisfaction


Important Note

Sprockets provides some directives that are placed inside of comments called require, require_tree, and require_self. DO NOT USE THEM IN YOUR SASS/SCSS FILES. They are very primitive and do not work well with Sass files. Instead, use Sass's native @import directive which sass-rails has customized to integrate with the conventions of your Rails projects.

**Comment by snitko** [comment]
Strangely, the bug went away. I'm not sure why. I never mixed `require` with `@import`.

**Comment by jasonfb** [comment]
are you sure there is no place in your app you have sprockets style ```#= require``` -- we found it in an old file, which wasn't even our primary SCSS file, and didn't even reference the imported SCSS vars we wanted. 

Our bug was reproducible and not intermittent, so in this case your bug may be a different issue

**Comment by snitko** [comment]
Just grepped it. No. No such place.
