### ISSUE TITLE
Invalid CSS after ".": expected class name, was ".rails-bootstra..."

### ISSUE THREAD

**Issue by mastertechrv** [rails/sass-rails#378]
![screen shot 2016-07-14 at 9 46 26 am 3](https://cloud.githubusercontent.com/assets/6068761/16845086/9f610040-49b5-11e6-9341-8ce0297ecbd7.png)

**Comment by rafaelfranca** [comment]
This error means there is something wrong in your css. It is not an issue in the gem.

**Comment by mastertechrv** [comment]
ive looked through my entire css file and i cant find any mistakes in my stylesheet

**Comment by rafaelfranca** [comment]
It complaining that expected a class name after a `.` but got `.rails-bootstrap...` start looking from that.
