### ISSUE TITLE
deprecation warnings with sprockets 3.7.0

### ISSUE THREAD

**Issue by maia** [rails/sass-rails#381]
sass-rails-5.0.5 throws deprecation warnings when using sprockets 3.7.0:
```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
(called from block (2 levels) in <class:Railtie> at /…/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:57)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
(called from block (2 levels) in <class:Railtie> at /…/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:58)
```

**Comment by polysaturate** [comment]
Quick fix for me(for now) was... 

`gem 'sprockets', '3.6.3'`

**Comment by jaredbeck** [comment]
Same warning in `js-routes` (https://github.com/railsware/js-routes/issues/201) I suspect a lot of sprockets extensions will be fixing this in similar ways and may benefit from each other's work.

**Comment by kapso** [comment]
Seeing same warning in https://github.com/ai/autoprefixer-rails

**Comment by rafaelfranca** [comment]
cc @schneems

**Comment by schneems** [comment]
Working on a PR.

**Comment by maia** [comment]
@schneems Thanks a lot for solving the issue with the release of 5.0.6!

**Comment by schneems** [comment]
Thanks all for chiming in. I added some docs to Sprockets guides on master to show how to register an processor across Sprockets 2, 3, and 4. Link: https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#registering-all-versions-of-sprockets-in-processors

I also re-wrote the guide to be easier to reference, put the most relevant examples at the top of the sections and added a table of contents at the top. Please take a look and if you have something to add or ways you think the docs could be better open an issue and we can talk about it. I want the process of maintaining Sprockets extensions to be as easy as possible, I'm hoping the docs can smooth out rough edges and cut down on guessing how to write a sprockets plugin.

If you're working on getting rid of deprecations in your own library and having problems, ping me on a pull request.

**Comment by calderJamNet** [comment]
hey @schneems , I just updated my gem library for the first time in a while and a bunch of css/scss (but not everything) is not loading correctly, and I'm also seeing this error. Is it likely that this is related? I've never really used sprockets before so its not really clear to me why this would be happening.

**Comment by schneems** [comment]
@calderJamNet if you have a repro example app please put it on github and give me access. If not you can manually specify an older version of sprockets and sass-rails in your Gemfile.lock.

Do you have any more details other than not working correctly?

**Comment by calderJamNet** [comment]
Hey @schneems, I added you to the repo. Its just a testing ground for front end styles so its kind of a mess. I did however notice the same changes when I updated all the gems in the main repo.

The differences I have noticed so far have only affected "border" and "color" css styles, with the original foundation styles being applied now while before they were being overwritten. They are minor and could be fixed easily with "!important" but I would like to understand why this started happening if possible.

This is how it was before bundle update:
![screen shot 2016-08-02 at 10 49 38 pm](https://cloud.githubusercontent.com/assets/8429695/17352348/f1dc23d8-5903-11e6-867d-e4d80430b19e.png)

This is how it is after: 
![screen shot 2016-08-02 at 10 49 27 pm](https://cloud.githubusercontent.com/assets/8429695/17352353/fe79cabe-5903-11e6-90f6-e5b4b32ed97f.png)


so far I've only noticed it affecting styles for founations ".accordion", so perhaps the issue is routed in something they changed, in which case I apologize for wasting your time.

**Comment by schneems** [comment]
@calderJamNet i'm back from vacation and will probably have time to look at this sometime this week. I made an issue for a reminder since this issue is "closed" https://github.com/rails/sass-rails/issues/384

**Comment by veborich** [comment]
>Thanks all for chiming in. I added some docs to Sprockets guides on master to show how to register an processor across Sprockets 2, 3, and 4. Link: https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#registering-all-versions-of-sprockets-in-processors

@schneems I haven't customized Sprockets before -- what's the typical file/location that you would place the `env` conditional code you provide in that link above?

**Comment by schneems** [comment]
>  I haven't customized Sprockets before

This deprecation should only come from gems that are customizing sprockets for you, what is the deprecation output say? It should point it at a location, probably from a gem.

**Comment by calderJamNet** [comment]
@schneems I haven't customized sprockets before this either. How do I view the deprecation output?

**Comment by schneems** [comment]
@calderJamNet i don't understand the question. If you're using Sprockets 3.7 and using another gem that doesn't support Sprockets 4 yet, then you'll see deprecation output in your output when you build assets or run in development.

**Comment by scarekr0w** [comment]
1) Add the sass rails gem to the the GemFile
      a) gem 'sass-rails', '~> 5.0', '>= 5.0.6'

2) Run gem install sass-rails on the terminal

2) Run bundle install
      a) bundle install --without production && bundle update

**Comment by scarekr0w** [comment]
1) Add the sass rails gem to the the GemFile
a) gem 'sass-rails', '~> 5.0', '>= 5.0.6'

2) Run gem install sass-rails on the terminal
  a) gem install sass-rails

3) Run bundle install
a) bundle install --without production && bundle update
