### ISSUE TITLE
Can't find functions in scss file

### ISSUE THREAD

**Issue by J77J** [rails/sass-rails#389]
Functions in my sass files are not being recognised, I've found a few possible solutions, but nothing has worked so far.. I'm sure it can't be anything too complex to fix, but I can't seem to find the solution. Is there anything obvious I might need to do to get this working?

I'm using rails 5.0.0.1 and sass-rails 5.0.6 (environment is development)

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
