### ISSUE TITLE
`rescue in block (2 levels) in require': There was an error while trying to load the gem 'sass-rails'. (Bundler::GemRequireError) Gem Load Error is: uninitialized constant Sass::Rails::Tilt

### ISSUE THREAD

**Issue by CristiAllan** [rails/sass-rails#393]
When I try to run my rails server with sass-rails at gemfile, my server don't run and show me this message,

Gem Load Error is: uninitialized constant Sass::Rails::Tilt

If I comment the line at gemfile, my server runs ok. 

How can I resolve this issue?

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?
