### ISSUE TITLE
Are we getting a sass-rails release with Rails 5.1?

### ISSUE THREAD

**Issue by Obversity** [rails/sass-rails#397]
I'm wondering whether we'll see a 6.0.0 release of this gem used in Rails 5.1. At the moment, the Rails-generated Gemfile references Github, rather than rubygems, for sass-rails. 

My company uses compass-rails in all of our projects, can compass-rails currently depends on sass-rails `< 5.1`, so for new Rails 5 projects, we'd either need to downgrade sass-rails, or if there's going to be a new release of sass-rails, maybe look at doing a pull request for compass-rails and hope their test coverage is good. (I know zilch about either sass-rails or compass-rails personally.)

**Comment by rafaelfranca** [comment]
sass-rails 5.0.4 already support Rails 5.2, so no, we are not having a new release of sass-rails with Rails 5.1. But I'll change the rails generator to use the released version instead the github reference. Thank you for the report
