### ISSUE TITLE
bundle (>=1.15.0) install fails

### ISSUE THREAD

**Issue by yairper** [rails/sass-rails#402]
Hi, I've noticed that when I run `bundle install` with Gemfile including version 4.0.3
I receive the following error:

**Downloading sass-rails-4.0.3 revealed dependencies not in the API or the lockfile (sass (~> 3.2.0)).
Either installing with `--full-index` or running `bundle update sass-rails` should fix the problem.**

notice it happens only with bundler 1.15.0+

**Comment by robin850** [comment]
Hello @yairper,

Actually this seems more like a Bundler feature than any sort of bug. The error message tells you what to do ; you can try to run it with `--full-index`.

Anyway, this version of sass-rails is 3 years old so even though if that was something to fix on our side, these release series aren't supported anymore.

I'm giving this a close but thanks for reporting anyway !
