### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$break-sm" undefined

### ISSUE THREAD

**Issue by davidpatters0n** [rails/sass-rails#405]
I'm having a problem whereby when I run: `Rails.application.assets.find_asset('foundation_emails').to_s` in my Rails test console it throws: 

```ruby
Loading test environment (Rails 4.2.8)
irb(main):001:0> Rails.application.assets.find_asset('foundation_emails').to_s
Sass::SyntaxError: Undefined variable: "$break-sm".
```

The above error appears to be very similar to the following issues #333 #379 #396. Issue #396 goes into a bit more depth and it appears as though the issue was moved to a sprockets issue https://github.com/rails/sprockets/issues/474. The latest comment on this issue suggest upgrading to version 3.0 of sprockets. This suggestion appears doesn't appear to not work.

I've also put together a dummy app: https://github.com/davidpatters0n/testApp for reference.

**Comment by adam-e-trepanier** [comment]
Having same issue.  In a current application I work on we use the font-awesome-gem.  I stepped thru the gem and it loads all asset paths and the @imports are working correctly.  One file can not see the variables of another sass file.
