### ISSUE TITLE
Rails 5.1 compatibility

### ISSUE THREAD

**Issue by Utopism** [rails/sass-rails#410]
Hi,
This is not really an issue, but do you know when the next 6.0 non beta version will be available (allowing Rails 5.1)?
Sprockets version 4 is needed to fix some issues with assets manifest in engines (like this one https://github.com/rails/sprockets/issues/415).
An it can only be available with a release relaxing rails 5.1 dependency.

Thanks a lot.

**Comment by Utopism** [comment]
If something prevents this beta version to be released, can we help ?

**Comment by VzqzAc** [comment]
Did you try this gem with rails 5.1? I see an already merged PR to allow rails 5.1 (actually, any < 6)

**Comment by Utopism** [comment]
I'm using Rails 5.1.4, but I'm preparing a training on current rails versions, and I can't tell to the people that they have to use a beta version of the gem...

**Comment by Utopism** [comment]
Hi again,

Among the 34 Issues, are there some that prevent this version to get out from a beta version ?
If yes, can we know which ones ? perhaps I can help to solve them.
If no can this gem be published as non-beta ?
The fact that this version is a beta locks sprockets to <4 which has issues with assets provided in engines.

**Comment by rafaelfranca** [comment]
The version 6 is on hold right now since the version 5.0 works fine with the current versions of rails and sprockets. We are only going to release a new version 6 when sprockets 4 is on the release candidate.
