### ISSUE TITLE
Rails 5 : Asset precompile failed when deploying to Heroku

### ISSUE THREAD

**Issue by NodeUrsa** [rails/sass-rails#416]
```
remote:        Sass::SyntaxError: $alpha: (0 0.9) is not a number for `rgba'
remote:        (sass):4982
remote:        /tmp/build_9b15d59eabe8f4b2edda98ccc4e53761/app/assets/config/manifest.js:3
remote:        (sass):4982
```
This is error when I get deploying to Heroku.

**Comment by adiakritos** [comment]
I have the same problem. I have to do `rails assets:precompile` before each deploy. This is making my commit history look totally screwed up but it's the only way I can figure out in the short term to deploy changes to my public assets.

**Comment by NodeUrsa** [comment]
@adiakritos This issue doesn't fixed yet. So I updated CSS to avoid this issue.
```
not filter: alpha (0, 0.9)
correct: filter: alpha(Opacity=90);
```
Hope this tip will help you.
