### ISSUE TITLE
sass version locked to ~3.1

### ISSUE THREAD

**Issue by qvolant** [rails/sass-rails#418]
https://github.com/rails/sass-rails/blob/5-0-stable/sass-rails.gemspec#L17

sass 3.1 is from 2012. Many frameworks/libraries today use maps which were introduced in sass 3.3 (from 2014)

latest sass-rails release was from november 2017. Why is it depending on technology from 2012 ?

**Comment by toncid** [comment]
You are wrong, the operator is somewhat misleading: `~> 3.1` means `>= 3.1 and < 4.0`. Check your `Gemfile.lock`:

```
    sass (3.7.2)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
```
