### ISSUE TITLE
Ruby Sass End-of-Life: 26 March 2019

### ISSUE THREAD

**Issue by chriseppstein** [rails/sass-rails#420]
This was announced about a month ago, but I wanted to make sure the Rails community is aware that the [Ruby implementation of Sass has been EOL'd](http://sass.logdown.com/posts/7081811).

TL;DR:
* The reference implementation of [Sass is now written in Dart](https://github.com/sass/dart-sass).
* Ruby Sass is maintained for security and CSS Compatibility issues through March 2019.
* Only PRs for the above mentioned reasons are being accepted at this time.
* The git repo for ruby sass is now officially at https://github.com/sass/ruby-sass
* The repo at https://github.com/sass/sass is now for implementation-agnostic language issues.
* On 26 March 2019, the deprecation period for Ruby Sass will end and it will no longer be maintained.

That is, unless, there's at least one new, active maintainer for the ruby implementation of Sass. Preferably more than one.

Rails needs a plan a plan to deal with this before the ruby version becomes unmaintained. If a first-class Sass implementation for the ruby and rails community is desired, hopefully a maintainer can be found. Otherwise, one of the other Sass implementations can be used (most likely through node/npm).

**Comment by EugenMayer** [comment]
any progress here?

**Comment by NARKOZ** [comment]
SassC requires CRuby

**Comment by jrochkind** [comment]
Generating a new default Rails 5.2 app gets you this deprecation warning. 

March 2019 is coming up, is there any news on what is expected?

**Comment by coorasse** [comment]
I personally started switching to Webpacker. 
Migration of existing apps it is pretty easy and it [will be the default Javascript compiler in Rails 6](https://github.com/rails/rails/pull/33079).
Migrating CSS is even easier than migrating JS. I leave here [a guide to do that](https://medium.com/@coorasse/goodbye-sprockets-welcome-webpacker-3-0-ff877fb8fa79).
I hope it will help someone else.

**Comment by Fudoshiki** [comment]
@coorasse I need simple css file for each page, not bundle, `Sprockets` do that easy, with `Webpack` this is no trivial task
Not for all sites need react and not all sites are SPA

**Comment by amalrik** [comment]
Ok 
now I see the thread on rails main repo and it seems its not possible to simple replace sass-rails with sassc-rails. So migrate to webpacker seems to be the way to go.

**Comment by jrochkind** [comment]
@amalrik can you link to the thread on rails main repo for us?

In my specific apps, I have switched to sassc-rails without problem. Although I have no trouble believing there are reasons it can't work universally. I am curious to see what is being discussed on rails repo.

**Comment by amalrik** [comment]
@jrochkind 
https://github.com/rails/rails/issues/32896

**Comment by jakeonfire** [comment]
@amalrik the tables have turned again in favor of `sassc-rails`:

https://github.com/rails/sass-rails/issues/420

**Comment by P9GIT** [comment]
@amalrik 

They are still contemplating simply replacing the sass processor with the sassc processor in sass-rails it seems: https://github.com/rails/rails/pull/34884#issuecomment-456919750

**Comment by guilleiguaran** [comment]
See https://github.com/rails/sass-rails/pull/424

**Comment by P9GIT** [comment]
@guilleiguaran 

Awesome! Thanks!
