### ISSUE TITLE
5.0.8 Release Needed?

### ISSUE THREAD

**Issue by SeanSith** [rails/sass-rails#429]
With the official release of Rails 6 an hour or so ago, a `rails new ...` fails with the following error message:

```
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      railties (= 6.0.0)

    sass-rails (~> 5) was resolved to 5.0.4, which depends on
      railties (>= 4.0.0, < 5.0)

    web-console (>= 3.3.0) was resolved to 4.0.0, which depends on
      railties (>= 6.0.0.a)

    webpacker (~> 4.0) was resolved to 4.0.7, which depends on
      railties (>= 4.2)
         run  bundle binstubs bundler
Could not find gem 'sass-rails (~> 5)' in any of the gem sources listed in your Gemfile.
       rails  webpacker:install
Could not find gem 'sass-rails (~> 5)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

I surmise that releasing an official 6.0.0 gem may alleviate these issues? Updating my Gemfile with 6.0.0.beta3 allows a subsequent `bundle install` within the newly created Rails project to install.

It seems that Rails is requiring `sass-rails, '~>5'` and I don't know which project is easier to move. I've opened a corresponding issue in rails/rails#36954

My environment is Ruby 2.6.3 installed with ruby-install and controlled with asdf.
Rails is `Rails 6.0.0` with no competing Rails versions installed.
Bundler 1.17.3 and 2.0.2 have both been attempted.

**Comment by rafaelfranca** [comment]
sass-rails 6.0.0 was released.

**Comment by rafaelfranca** [comment]
Thank you for reporting
