### ISSUE TITLE
url imports aren't loaded in 6.0

### ISSUE THREAD

**Issue by PQALAB** [rails/sass-rails#431]
When I try to load a font asset via an email, I get an error would precompiling in production and in development the font is not loaded at all.

problem url
`@import 'https://fonts.googleapis.com/icon?family=Material+Icons';`

Production error
`SassC::SyntaxError: Error: @import directive requires a url or quoted path`

I can get around it by downgrading to 5.1

**Comment by rafaelfranca** [comment]
sassc behaves differently from Ruby sass and sass-rails 6 is using sassc. If you found an incompatibility problem please report to sassc-rails https://github.com/sass/sassc-rails#libsass-compatibility-with-ruby-sass.
