### ISSUE TITLE
SassC::SyntaxError: Error: malformed URL

### ISSUE THREAD

**Issue by rachmatm** [rails/sass-rails#434]
on line 1:9 of ../../../.rvm/gems/ruby-2.6.0/gems/active_skin-0.0.12/app/assets/stylesheets/active_skin.sass
from line 19:1 of app/assets/stylesheets/active_admin.css.scss

    @import url(//fonts.googleapis.com/css?family=Source+Sans+Pro:400,"600","700

error when compiling:
https://github.com/SoftwareBrothers/active_skin/blob/master/app/assets/stylesheets/active_skin.sass#L1

Please give me the best solution to this issue, thank you.

**Comment by rafaelfranca** [comment]
the gem you are using doesn't work with sassc. You need to open an issue on that gem. Thank you for reporting.
