### ISSUE TITLE
Modern color syntax

### ISSUE THREAD

**Issue by o-t-w** [rails/sass-rails#443]
Apologies if this is the wrong place to raise an issue (I assume this is where the error is coming from) but I am getting an error about "wrong number of arguments" for valid modern CSS color syntax. 

```
color: hsl(200deg 80% 39%);
```

<img width="822" alt="Screenshot 2021-10-19 at 12 20 20" src="https://user-images.githubusercontent.com/29547922/137903866-acf4e278-af3f-40ef-ab74-601e686ec42a.png">

**Comment by rafaelfranca** [comment]
This is an issue on sassc. Please report there.

**Comment by o-t-w** [comment]
You shouldn’t be using sassc: “ Warning: LibSass and SassC are deprecated. While it will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. **Projects that still use it should move onto Dart Sass**.” @rafaelfranca

**Comment by rafaelfranca** [comment]
Well, so I guess you will need to move onto Dart Sass or keep using the old color syntax.

**Comment by o-t-w** [comment]
@rafaelfranca Shouldn't _this project_ also do that?

**Comment by rafaelfranca** [comment]
This project is just a wrapper on top of sassc. We don't add new feature to it, all features are provided by sassc. Moving onto Dart is not in our plans. Rails 7 will include cssbundling-rails instead of sass-rails.
