### ISSUE TITLE
image-url helper only works on development

### ISSUE THREAD

**Issue by luan** [rails/sass-rails#45]
I am using `image-url("image.png")` in my .scss file to correctly insert the asset path there.
In development it works great. But in production the compiled .css file still has `image-url("image.png")` and not `url(/assets/images-#####.png)`.

My environment:

**in development.rb:**

``` ruby
  config.assets.compress = false
  config.assets.debug = true
```

**in production.rb:**

``` ruby
  config.assets.compress = false
  config.assets.compile = true
  config.assets.digest = true
```

**Comment by lapenz** [comment]
Luan, Im using image-url("image.png") at Rails 5.2.1.1 and sass-rails 5.0 on my application.scss and its all work fine. My production.rb just have config.assets.compile = false
